const npySummerProm=[
    {
        nom:'Maison d\'Orride',
        type:'Hotels / Chambres d\'hôtes',
        loc:'Ledeuix',
        station:'Lpsm',
        ui:'OSCH-72613',
        pic:'maison-orride.jpg',
        lat:43.242881, 
        lng:-0.607716,
        capacite:0,
        tarif:'',
        duree:'',

    },
    {
        nom:'Flocons du soleil',
        type:'Appartement',
        loc:'Peyragudes',
        station:'Peyragudes',
        ui:'OSMB-64622',
        pic:'placeholder.jpg',
        lat:42.794963,
        lng:0.443261,
        capacite:0,
        tarif:'',
        duree:'',

    },
    {
        nom:'Maison de Peyragudes',
        type:'Appartements',
        loc:'Peyragudes',
        station:'Peyragudes',
        ui:'MARK-42660',
        pic:'maison_de_peyragudes.jpg',
        lat:0,
        lng:0,
       capacite:0,
        tarif:'',
        duree:'',

    },
    {
        nom:'Agence pic du midi',
        type:'Appartements',
        loc:'La Mongie',
        station:'Tourmalet',
        ui:'ZEPH-64477',
        pic:'agence_picdumidi.jpg',
        lat:0,
        lng:0,
       capacite:0,
        tarif:'',
        duree:'',

    },
    {
        nom:'Hostellerie de Ramonjuan',
        type:'Hotels / Chambres d\'hôtes',
        loc:'B. de Bigorre',
        station:'Tourmalet',
        ui:'AVAI-39677',
        pic:'domaine-ramonjuan.jpg',
        lat:42.988780,
        lng:0.109380,
        capacite:0,
        tarif:'',
        duree:'',

    },
    {
        nom:'Mer & Golf Pic du Midi',
        type:'Résidences de tourisme',
        loc:'La Mongie',
        station:'Tourmalet',
        ui:'AVAI-43796',
        pic:'meretgolf-pic.jpg',
        lat:42.910431,
        lng:0.171008,
       capacite:0,
        tarif:'',
        duree:'',


    },
    {
        nom:'Mer & Golf La Mongie',
        type:'Résidences de tourisme',
        loc:'La Mongie',
        station:'Tourmalet',
        ui:'AVAI-43794',
        pic:'meretgolf-tourmalet.jpg',
        lat:42.911829,
        lng:0.174001,
        capacite:0,
        tarif:'',
        duree:'',

    },
    {
        nom:'Résidence Richelieu',
        type:'Appartements',
        loc:'La Pierre St Martin',
        station:'Lpsm',
        ui:'OSMB-35536',
        pic:'residence_richelieu.jpg',
        lat:0,
        lng:0,
        capacite:0,
        tarif:'',
        duree:'',

    },
    {
        nom:'Résidence Gascogne',
        type:'Appartements',
        loc:'Gourette',
        station:'Gourette',
        ui:'OSMB-108746-1',
        pic:'residence_gascogne.jpg',
        lat:42.970744,
        lng:-0.390991,
        capacite:0,
        tarif:'',
        duree:'',

    },
    {
        nom:'Le Bois Joli',
        type:'Hotels / Chambres d\'hôtes',
        loc:'Cauterets',
        station:'Cauterets',
        ui:'HRIT-35250',
        pic:'hotel-boisjoli.jpg',
        lat:42.888554,
        lng:-0.113872,
        capacite:0,
        tarif:'',
        duree:'',

    },
    {
        nom:'Carré Py',
        type:'Hotels / Chambres d\'hôtes',
        loc:'B. de Bigorre',
        station:'Tourmalet',
        ui:'AVAI-47066',
        pic:'hotel-carrepy.jpg',
        lat:43.055462,
        lng: 0.157509,
        capacite:0,
        tarif:'',
        duree:'',

    },
    {
        nom:'La Maisonnée',
        type:'Hotels / Chambres d\'hôtes',
        loc:'Sazos',
        station:'Luz-Ardiden',
        ui:'OSCH-48058',
        pic:'gite_la_maisonnee.jpg',
        lat:42.884124,
        lng: -0.025394,
        capacite:0,
        tarif:'',
        duree:'',

    },
    {
        nom:'Camping de l\'Adour',
        type:'Campings',
        loc:'Gerde',
        station:'Tourmalet',
        ui:'OSCA-40376',
        pic:'camping_adour.jpg',
        lat:43.052779,
        lng: 0.159368,
        capacite:0,
        tarif:'',
        duree:'',

    },
    {
        nom:'Ecovillage Vacance Soleil du Pibeste',
        type:'Campings',
        loc:'Agos Vidalos',
        station:'Luz',
        ui:'CVERT-36125',
        pic:'camping-pibeste.jpg',
        lat:43.035626, 
        lng:-0.070879,
        capacite:0,
        tarif:'',
        duree:'',

    },
    {
        nom:'Les 4 Ours',
        type:'Hotels / Chambres d\'hôtes',
        loc:'Piau Engaly',
        station:'Piau',
        ui:'NOVH-47375',
        pic:'hotel-4ours.jpg',
        lat:42.783880, 
        lng:0.159078,
        capacite:0,
        tarif:'',
        duree:'',

    },
    {
        nom:'Auberge de l\'étable',
        type:'Hotels / Chambres d\'hôtes',
        loc:'Montory',
        station:'Lpsm',
        ui:'HRIT-29997',
        pic:'auberge-etable.jpg',
        lat:43.098069,
        lng:-0.817631,
        capacite:0,
        tarif:'',
        duree:'',

    },
    {
        nom:'Selection Agence Barroso',
        type:'Hotels / Chambres d\'hôtes',
        loc:'Gourette',
        station:'Gourette',
        ui:'HRES-36724',
        pic:'agence_barroso.jpg',
        lat:0,
        lng:0,
        capacite:0,
        tarif:'',
        duree:'',

    },
    {
        nom:'Les Adrets',
        type:'Résidences de tourisme',
        loc:'Peyragudes',
        station:'Peyragudes',
        ui:'OSMB-43060',
        pic:'residence_adrets.jpg',
        lat:42.796258,
        lng:0.438932,
        capacite:0,
        tarif:'',
        duree:'',

    },
    {
        nom:'Appartement Toit',
        type:'Résidences de tourisme',
        loc:'Peyragudes',
        station:'Peyragudes',
        ui:'OSMB-109565',
        pic:'appart_toit.jpg',
        lat:0,
        lng:0,
        capacite:0,
        tarif:'',
        duree:'',

    },
    {
        nom:'Sélection Page Immobilier',
        type:'Appartement',
        loc:'Cauterets',
        station:'Cauterets',
        ui:'OSMB-109565',
        pic:'placeholder.jpg',
        lat:0,
        lng:0,
        capacite:0,
        tarif:'',
        duree:'',

    }, 
    {
        nom:'Agence Square Habitat Barèges',
        type:'Appartement',
        loc:'Barèges',
        station:'Barèges',
        ui:'HELI-69350',
        pic:'placeholder.jpg',
        lat:0,
        lng:0,
        capacite:0,
        tarif:'',
        duree:'',

    },
    {
        nom:'Agence Square Habitat La Mongie',
        type:'Appartement',
        loc:'La Mongie',
        station:'La Mongie',
        ui:'HELI-69285',
        pic:'placeholder.jpg',
        lat:0,
        lng:0,
        capacite:0,
        tarif:'',
        duree:'',

    },
    {
        nom:'Agence Square Habitat Luz',
        type:'Appartement',
        loc:'Luz',
        station:'Luz',
        ui:'HELI-69352',
        pic:'placeholder.jpg',
        lat:0,
        lng:0,
        capacite:0,
        tarif:'',
        duree:'',

    },
    {
        nom:'Agence Square Habitat Cauterets',
        type:'Appartement',
        loc:'Cauterets',
        station:'Cauterets',
        ui:'HELI-69351',
        pic:'placeholder.jpg',
        lat:0,
        lng:0,
        capacite:0,
        tarif:'',
        duree:'',

    },
    {
        nom:'Agence Square Habitat Gourette',
        type:'Appartement',
        loc:'Gourette',
        station:'Gourette',
        ui:'HELI-69353',
        pic:'placeholder.jpg',
        lat:0,
        lng:0,
        capacite:0,
        tarif:'',
        duree:'',

    },
    

    //Loueurs particuliers
    {
        nom:'Arcizettes 2',
        type:'Appartement',
        loc:'Gourette',
        station:'Gourette',
        ui:'OSMB-64221-2',
        pic:'arcizettes.jpg',
        lat:42.958021,
        lng:-0.333110,
        capacite:4,
        tarif:'120',
        duree:'semaine',

    },
    {
        nom:'Campbielh 2',
        type:'Appartement',
        loc:'Piau',
        station:'Piau',
        ui:'OSMB-92961-2',
        pic:'campbielh2.jpg',
        lat:42.784206, 
        lng:0.159462,
        capacite:4,
        tarif:'27',
        duree:'nuit',

    },
    {
        nom:'Ramondia 405',
        type:'Appartement',
        loc:'Piau',
        station:'Piau',
        ui:'OSMB-39493-1',
        pic:'ramondia405.jpg',
        lat:42.783694,
        lng: 0.161321,
        capacite:4,
        tarif:'250',
        duree:'semaine',

    },
    {
        nom:'Chalet 72',
        type:'Appartement',
        loc:'La Pierre St martin',
        station:'Lpsm',
        ui:'OSMB-70818-1',
        pic:'chalet72.jpg',
        lat:42.977093, 
        lng:-0.742837,
        capacite:6,
        tarif:'75',
        duree:'nuit',

    },
    {
        nom:'Mongie 1900',
        type:'Appartement',
        loc:'La Mongie',
        station:'Tourmalet',
        ui:'OSMB-93431-1',
        pic:'mongie1900.jpg',
        lat:42.911939,
        lng:0.176423,
        capacite:4,
        tarif:'nuit',
        duree:'nuit',

    },
    {
        nom:'Neouvielle',
        type:'Appartement',
        loc:'Piau Engaly',
        station:'Piau',
        ui:'OSMB-39476-6',
        pic:'neouvielle.jpg',
        lat:42.785044, 
        lng:0.158978,
        capacite:8,
        tarif:'95',
        duree:'nuit',

    },
    {
        nom:'Pascal S.',
        type:'Appartement',
        loc:'Barèges',
        station:'Tourmalet',
        ui:'OSMB-93370-1',
        pic:'apptpascals.jpg',
        lat:42.895196, 
        lng:0.061583,
        capacite:6,
        tarif:'250',
        duree:'semaine',
    },
    {
        nom:'Chateau de Beost',
        type:'Appartement',
        loc:'Gourette',
        station:'Gourette',
        ui:'OSMB-71493-1',
        pic:'chateau_beost.jpg',
        lat:42.993772,
        lng:-0.415816,
        capacite:7,
        tarif:'60',
        duree:'nuit',
    },
    {
        nom:'Appartement 5',
        type:'Appartement',
        loc:'Cauterets',
        station:'Cauterets',
        ui:'OSMB-92162-1',
        pic:'appartement5.jpg',
        lat:42.891183, 
        lng:-0.117219,
        capacite:5,
        tarif:'60',
        duree:'nuit',
    },
    {
        nom:'Michele S.',
        type:'Appartement',
        loc:'Cauterets',
        station:'Cauterets',
        ui:'OSMB-35623-6',
        pic:'apptmicheles.jpg',
        lat:42.885210,
        lng: -0.111638,
        capacite:4,
        tarif:'450',
        duree:'semaine',
    },
    {
        nom:'La Mongie 1800',
        type:'Appartement',
        loc:'La Mongie',
        station:'Tourmalet',
        ui:'OSMB-47648-1',
        pic:'mongie1800.jpg',
        lat:42.911990, 
        lng:0.176604,
        capacite:4,
        tarif:'50',
        duree:'nuit',
    },
     {
        nom:'Lehailla',
        type:'Appartement',
        loc:'La Mongie',
        station:'Tourmalet',
        ui:'OSMB-40211-1',
        pic:'lehailla.jpg',
        lat:43.112639, 
        lng:0.203907,
        capacite:5,
        tarif:'320',
         duree:'semaine',
    },
     {
        nom:'Maison Domer',
        type:'Appartement',
        loc:'Cauterets',
        station:'Cauterets',
        ui:'OSMB-35698-9',
        pic:'maisondomer.jpg',
        lat:42.886800, 
        lng:-0.113727,
        capacite:7,
        tarif:'400',
         duree:'semaine',
    },
     {
        nom:'Maison Domer 2',
        type:'Appartement',
        loc:'Cauterets',
        station:'Cauterets',
        ui:'OSMB-35698-6',
        pic:'maisondomer2.jpg',
        lat:42.886800, 
        lng:-0.113728,
        capacite:6,
        tarif:'400',
         duree:'semaine',
    },
     {
        nom:'Maison Domer 3',
        type:'Appartement',
        loc:'Cauterets',
        station:'Cauterets',
        ui:'OSMB-35698-7',
        pic:'maisondomer3.jpg',
        lat:42.886800, 
        lng:-0.113729,
        capacite:7,
        tarif:'400',
         duree:'semaine',
    },
     {
        nom:'Maison Domer 4',
        type:'Appartement',
        loc:'Cauterets',
        station:'Cauterets',
        ui:'OSMB-35698-10',
        pic:'maisondomer4.jpg',
        lat:42.886800, 
        lng:-0.113730,
        capacite:7,
        tarif:'400',
         duree:'semaine',
    },
    {
        nom:'Maison Domer 5',
        type:'Appartement',
        loc:'Cauterets',
        station:'Cauterets',
        ui:'OSMB-35698-8',
        pic:'maisondomer5.jpg',
        lat:42.886800, 
        lng:-0.113731,
        capacite:4,
        tarif:'350',
        duree:'semaine',
    },
    {
        nom:'Meublé Domer 1',
        type:'Appartement',
        loc:'Cauterets',
        station:'Cauterets',
        ui:'OSMB-35698-4',
        pic:'meuble_domer.jpg',
        lat:42.886800, 
        lng:-0.113732,
        capacite:8,
        tarif:'600',
        duree:'semaine',
    },
    {
        nom:'Meublé Domer 2',
        type:'Appartement',
        loc:'Cauterets',
        station:'Cauterets',
        ui:'OSMB-35698-1',
        pic:'meuble_domer2.jpg',
        lat:42.886800, 
        lng:-0.113733,
        capacite:6,
        tarif:'400',
        duree:'semaine',
    },
    {
        nom:'Jerome P.',
        type:'Appartement',
        loc:'La Mongie',
        station:'Tourmalett',
        ui:'OSMB-64018-1',
        pic:'apptjeromep.jpg',
        lat:43.063839,
        lng: 0.146531,
        capacite:3,
        tarif:'270',
        duree:'semaine',
    },
    {
        nom:'Chantal D.',
        type:'Appartement',
        loc:'Cauterets',
        station:'Cauterets',
        ui:'OSMB-35677-1',
        pic:'apptchantald.jpg',
        lat:42.887050,
        lng:-0.113088,
        capacite:4,
        tarif:'350',
        duree:'semaine',
    },
    {
        nom:'Christophe D.',
        type:'Appartement',
        loc:'Cauterets',
        station:'Cauterets',
        ui:'OSMB-63759-1',
        pic:'apptchristophed.jpg',
        lat:42.887409, 
        lng:-0.113220,
        capacite:7,
        tarif:'105',
        duree:'nuit',
    },
    {
        nom:'Residence Le Mahourat',
        type:'Appartement',
        loc:'La Pierre St Martin',
        station:'Lpsm',
        ui:'OSMB-59764-1',
        pic:'residence_le_mahourat.jpg',
        lat:42.977506,
        lng:-0.744980,
        capacite:4,
        tarif:'220',
        duree:'semaine',
    },
    {
        nom:'Val Soleil',
        type:'Appartement',
        loc:'Gourette',
        station:'Gourette',
        ui:'OSMB-64414-1',
        pic:'val_soleil.jpg',
        lat:42.959073,
        lng:-0.332202,
        capacite:6,
        tarif:'55',
        duree:'nuit',
    },
    {
        nom:'Helios',
        type:'Appartement',
        loc:'Barèges',
        station:'Tourmalet',
        ui:'OSMB-47242-1',
        pic:'helios.jpg',
        lat:42.896153,
        lng:0.061040,
        capacite:6,
        tarif:'53',
        duree:'nuit',
    },
    {
        nom:'Gîte Campan',
        type:'Gîte',
        loc:'La Mongie',
        station:'Tourmalet',
        ui:'OSMB-93179-1',
        pic:'gite_campan.jpg',
        lat:43.007599,
        lng:0.187871,
        capacite:6,
        tarif:'85',
        duree:'nuit',
    },
    {
        nom:'Les Myrtilles',
        type:'Appartement',
        loc:'La Pierre St Martin',
        station:'Lpsm',
        ui:'OSMB-99541-1',
        pic:'lesmyrtilles.jpg',
        lat:42.977653, 
        lng:-0.744662,
        capacite:4,
        tarif:'250',
        duree:'semaine',
    },
    {
        nom:'Chalet de montagne',
        type:'Appartement',
        loc:'La Mongie',
        station:'Tourmalet',
        ui:'OSMB-102481-1',
        pic:'chalet_de_montagnes.jpg',
        lat:42.966249, 
        lng:0.229813,
        capacite:9,
        tarif:'130',
        duree:'semaine',
    },
    {
        nom:'Studio Cauterets',
        type:'Appartement',
        loc:'Cauterets',
        station:'Cauterets',
        ui:'OSMB-68297-3',
        pic:'studio_cauterets.jpg',
        lat:42.888686, 
        lng:-0.113489,
        capacite:3,
        tarif:'220',
        duree:'semaine',
    },
    {
        nom:'Club 2',
        type:'Appartement',
        loc:'Piau Engaly',
        station:'Piau',
        ui:'OSMB-65885-1',
        pic:'clubII_n52.jpg',
        lat:42.783268, 
        lng:0.159856,
        capacite:4,
        tarif:'250',
        duree:'semaine',
    },
    {
        nom:'Mongie Tourmalet',
        type:'Appartement',
        loc:'La Mongiee',
        station:'Tourmalet',
        ui:'OSMB-63857-1',
        pic:'mongietourmalet.jpg',
        lat:42.909237, 
        lng:0.167143,
        capacite:8,
        tarif:'200',
        duree:'semaine',
    },
    {
        nom:'Résidence Anglas',
        type:'Appartement',
        loc:'Gourette',
        station:'Gourette',
        ui:'OSMB-65564-1',
        pic:'residence_anglas.jpg',
        lat:42.958202, 
        lng:-0.333473,
        capacite:6,
        tarif:'455',
        duree:'semaine',
    },
    {
        nom:'Bero Bisto',
        type:'Appartement',
        loc:'La Mongie',
        station:'Tourmalet',
        ui:'OSMB-64735-1',
        pic:'bero_bisto_n7.jpg',
        lat:42.910905, 
        lng:0.174210,
        capacite:6,
        tarif:'50',
        duree:'nuit',
    },
    {
        nom:'Myrtilles 1',
        type:'Appartement',
        loc:'Piau Engaly',
        station:'Piau',
        ui:'OSMB-64985-1',
        pic:'myrtilles1.jpg',
        lat:42.782992,
        lng: 0.159415,
        capacite:4,
        tarif:'40',
        duree:'nuit',
    },
    {
        nom:'Myrtilles 2',
        type:'Appartement',
        loc:'Piau Engaly',
        station:'Piau',
        ui:'OSMB-64985-2',
        pic:'myrtilles1_surpistes.jpg',
        lat:42.782992,
        lng: 0.159415,
        capacite:4,
        tarif:'38',
        duree:'nuit',
    },
    {
        nom:'Myrtilles 3',
        type:'Appartement',
        loc:'Piau Engaly',
        station:'Piau',
        ui:'OSMB-64985-3',
        pic:'myrtilles1_surpistes.jpg',
        lat:42.782992,
        lng: 0.159415,
        capacite:5,
        tarif:'50',
        duree:'nuit',
    },
    {
        nom:'Appartement centre-ville',
        type:'Appartement',
        loc:'Cauterets',
        station:'Cauterets',
        ui:'OSMB-47776-1',
        pic:'appt_centreville.jpg',
        lat:42.887581, 
        lng:-0.113632,
        capacite:4,
        tarif:'300',
        duree:'semaine',
    },
    {
        nom:'La bergerie',
        type:'Appartement',
        loc:'La Mongie',
        station:'Tourmalet',
        ui:'OSMB-92299-1',
        pic:'la_bergerie.jpg',
        lat:43.101881, 
        lng:0.075124,
        capacite:6,
        tarif:'84',
        duree:'nuit',
    },
    {
        nom:'Bois de Marie',
        type:'Appartement',
        loc:'Barèges',
        station:'Tourmalet',
        ui:'OSMB-63637-1',
        pic:'bois_de_marie.jpg',
        lat:42.898234, 
        lng:0.067935,
        capacite:10,
        tarif:'108',
        duree:'nuit',
    },
    {
        nom:'Eric & Marie D.',
        type:'Appartement',
        loc:'Cauterets',
        station:'Cauterets',
        ui:'OSMB-90291-1',
        pic:'appt_ericmaried.jpg',
        lat:42.889746, 
        lng:-0.115991,
        capacite:6,
        tarif:'90',
        duree:'nuit',
    },
    {
        nom:'La Mongie 1900',
        type:'Appartement',
        loc:'La Mongie',
        station:'Tourmalet',
        ui:'OSMB-108617-1',
        pic:'lamongie_1900-2.jpg',
        lat:42.912008, 
        lng:0.176309,
        capacite:5,
        tarif:'200',
        duree:'semaine',
    },
    {
        nom:'Balcons de Barèges',
        type:'Appartement',
        loc:'Barèges',
        station:'Tourmalet',
        ui:'OSMB-63024-1',
        pic:'balcons_bareges.jpg',
        lat:42.895490,
        lng:0.061768,
        capacite:4,
        tarif:'200',
        duree:'semaine',
    },
    {
        nom:'Oursons 1',
        type:'Appartement',
        loc:'La Pierre St Martin',
        station:'Lpsm',
        ui:'OSMB-43309-1',
        pic:'lesoursons1_appt203.jpg',
        lat:42.978476, 
        lng:-0.745650,
        capacite:4,
        tarif:'40',
        duree:'nuit',
    },
    {
        nom:'Oursons 2',
        type:'Appartement',
         loc:'La Pierre St Martin',
        station:'Lpsm',
        ui:'OSMB-43309-6',
        pic:'lesoursons1_appt206.jpg',
        lat:42.978476, 
        lng:-0.745651,
        capacite:4,
        tarif:'40',
        duree:'nuit',
    },
    {
        nom:'Myrtilles 2',
        type:'Appartement',
        loc:'La Pierre St Martin',
        station:'Lpsm',
        ui:'OSMB-43324-1',
        pic:'lesmyrtilles_2.jpg',
        lat:42.976699, 
        lng:-0.744734,
        capacite:4,
        tarif:'75',
        duree:'nuit',
    },
    {
        nom:'Estrelias',
        type:'Maison',
        loc:'Cauterets',
        station:'Cauterets',
        ui:'OSMB-101074-1',
        pic:'maisondevacs_estrelias.jpg',
        lat:42.893193, 
        lng:-0.117409,
        capacite:10,
        tarif:'320',
        duree:'nuit',
    },
    {
        nom:'Le Martin pêcheur',
        type:'Appartement',
        loc:'La Mongie',
        station:'Tourmalet',
        ui:'OSMB-43754-1',
        pic:'studio_lemartinpecheur.jpg',
        lat:43.065583, 
        lng:0.151460,
        capacite:4,
        tarif:'190',
        duree:'semaine',
    },
    {
        nom:'Palmiers des vignaux 1',
        type:'Appartement',
        loc:'B. de Bigorre',
        station:'Tourmalet',
        ui:'OSMB-43754-2',
        pic:'lespalmiersdesvignaux.jpg',
        lat:43.066703,
        lng: 0.148256,
        capacite:6,
        tarif:'87',
        duree:'nuit',
    },
    {
        nom:'Palmiers des vignaux 2',
        type:'Appartement',
        loc:'B. de Bigorre',
        station:'Tourmalet',
        ui:'OSMB-43754-3',
        pic:'lespalmiersdesvignaux2.jpg',
        lat:43.066632, 
        lng:0.148260,
        capacite:2,
        tarif:'50',
        duree:'nuit',
    },
    {
        nom:'Palmiers des vignaux 3',
        type:'Appartement',
        loc:'B. de Bigorre',
        station:'Tourmalet',
        ui:'OSMB-43754-4',
        pic:'lespalmiersdesvignaux3.jpg',
        lat:43.066671, 
        lng:0.148209,
        capacite:2,
        tarif:'50',
        duree:'nuit',
    },
    {
        nom:'Palmiers des vignaux 4',
        type:'Appartement',
        loc:'B. de Bigorre',
        station:'Tourmalet',
        ui:'OSMB-43754-5',
        pic:'lespalmiersdesvignaux4.jpg',
        lat:43.066650, 
        lng:0.148279,
        capacite:3,
        tarif:'69',
        duree:'nuit',
    },
    {
        nom:'Le Lapiaz',
        type:'Appartement',
        loc:'La Pierre St Martin',
        station:'Lpsm',
        ui:'OSMB-43314-1',
        pic:'chalet_le_lapiaz.jpg',
        lat:42.977733, 
        lng:-0.742571,
        capacite:6,
        tarif:'450',
        duree:'semaine',
    },
    {
        nom:'Myrtilles 3',
        type:'Appartement',
        loc:'La Pierre St Martin',
        station:'Lpsm',
        ui:'OSMB-47100-1',
        pic:'lesmyrtilles_3.jpg',
        lat:42.976736,
        lng: -0.744646,
        capacite:4,
        tarif:'170',
        duree:'semaine',
    },
    {
        nom:'Myrtilles 4',
        type:'Appartement',
        loc:'La Pierre St Martin',
        station:'Lpsm',
        ui:'OSMB-47100-2',
        pic:'lesmyrtilles_4.jpg',
        lat:42.976657, 
        lng:-0.744637,
        capacite:4,
        tarif:'170',
        duree:'semaine',
    },
    {
        nom:'Studio',
        type:'Appartement',
        loc:'Cauterets',
        station:'Cauterets',
        ui:'OSMB-71074-1',
        pic:'studio_lafuentejc.jpg',
        lat:42.891287, 
        lng:-0.113549,
        capacite:4,
        tarif:'38',
        duree:'nuit',
    },
    {
        nom:'Oursons 2',
        type:'Appartement',
        loc:'La Pierre St Martin',
        station:'Lpsm',
        ui:'OSMB-47594-1',
        pic:'lesoursonsII.jpg',
        lat:42.977578, 
        lng:-0.744298,
        capacite:4,
        tarif:'35',
        duree:'nuit',
    },
    {
        nom:'Gîte Lascurettes',
        type:'Gîte',
        loc:'Beost',
        station:'Gourette',
        ui:'OSMB-92421-1',
        pic:'gite_lascurette.jpg',
        lat:0,
        lng:0,
        capacite:10,
        tarif:'200',
        duree:'nuit',
    },
    {
        nom:'Jean Michel C.',
        type:'Appartement',
        loc:'Cauterets',
        station:'Cauterets',
        ui:'OSMB-67557-1',
        pic:'studio_jeanmichelc.jpg',
        lat:42.890723, 
        lng:-0.113322,
        capacite:3,
        tarif:'45€',
        duree:'nuit',
    },
    {
        nom:'Plein Soleil',
        type:'Appartement',
        loc:'La Pierre St Martin',
        station:'Lpsm',
        ui:'OSMB-100218-1',
        pic:'plein_soleil.jpg',
        lat:42.977303, 
        lng:-0.745014,
        capacite:6,
        tarif:'50',
        duree:'nuit',
    },
    {
        nom:'Club Engaly 2',
        type:'Appartement',
        loc:'Piau Engaly',
        station:'Piau',
        ui:'OSMB-63933-1',
        pic:'club_engalyII_n61.jpg',
        lat:42.783313, 
        lng:0.159846,
        capacite:4,
        tarif:'250',
        duree:'semaine',
    },
    {
        nom:'Appartement cosy',
        type:'Appartement',
        loc:'Cauterets',
        station:'Cauterets',
        ui:'OSMB-73884-1',
        pic:'appt_cosy_ctrville.jpg',
        lat:42.887634, 
        lng:-0.113883,
        capacite:4,
        tarif:'55',
        duree:'nuit',
    },
    {
        nom:'Appartement Mongie Tourmalet 1',
        type:'Appartement',
        loc:'La Mongie',
        station:'Tourmalet',
        ui:'OSMB-40205-1',
        pic:'residence_mongietourmalet.jpg',
        lat:42.908876, 
        lng:0.166634,
        capacite:6,
        tarif:'220',
        duree:'semaine',
    },
    {
        nom:'Appartement Mongie Tourmalet 2',
        type:'Appartement',
        loc:'La Mongie',
        station:'Tourmalet',
        ui:'OSMB-40205-2',
        pic:'residence_mongietourmalet2.jpg',
        lat:42.908865, 
        lng:0.166662,
        capacite:4,
        tarif:'180',
        duree:'semaine',
    },
    {
        nom:'Port Engaly 2',
        type:'Appartement',
        loc:'Piau Engaly',
        station:'Piau',
        ui:'OSMB-47485-1',
        pic:'port_engaly2.jpg',
        lat:42.784620, 
        lng:0.157075,
        capacite:7,
        tarif:'210',
        duree:'semaine',
    },
    {
        nom:'Maison de Pierres',
        type:'Maison',
        loc:'Peyragudes',
        station:'Peyragudes',
        ui:'OSMB-68287-1',
        pic:'maison_pierres.jpg',
        lat:42.812604, 
        lng:0.496831,
        capacite:6,
        tarif:'360',
        duree:'semaine',
    },
    {
        nom:'Panoramic',
        type:'Appartement',
        loc:'La Mongie',
        station:'Tourmalet',
        ui:'OSMB-65727-1',
        pic:'panoramic.jpg',
        lat:0,
        lng:0,
        capacite:5,
        tarif:'250',
        duree:'semaine',
    },
    {
        nom:'Escargot Bleu',
        type:'Gîte',
        loc:'Oloron Ste Marie',
        station:'Lpsm',
        ui:'OSMB-109227-1',
        pic:'gite_escargot_bleu.jpg',
        lat:43.180004,
        lng: -0.640976,
        capacite:4,
        tarif:'95',
        duree:'nuit',
    },
    {
        nom:'Appartement Le Serias',
        type:'Appartement',
        loc:'Peyragudes',
        station:'Peyragudes',
        ui:'OSMB-109209-1',
        pic:'residence_le_serias.jpg',
        lat:42.791178,
        lng: 0.446940,
        capacite:8,
        tarif:'500',
        duree:'semaine',
    },
    {
        nom:'Montana N314',
        type:'Appartement',
        loc:'La Mongie',
        station:'La Mongie',
        ui:'OSMB-92755-2',
        pic:'montana_n314.jpg',
        lat:42.908839, 
        lng:0.167116,
        capacite:4,
        tarif:'400',
        duree:'semaine',
    },
    {
        nom:'Appartement Pied télécabine',
        type:'Appartement',
        loc:'Cauterets',
        station:'Cauterets',
        ui:'OSMB-71188-2',
        pic:'appartementt2_piedtelecabine.jpg',
        lat:42.890889, 
        lng:-0.113267,
        capacite:4,
        tarif:'320',
        duree:'semaine',
    },
    {
        nom:'Résidence Les Myrtilles',
        type:'Appartement',
        loc:'La Pierre St Martin',
        station:'Lpsm',
        ui:'OSMB-63259-1',
        pic:'residence_lesmyrtilles.jpg',
        lat:42.976688,
        lng:-0.744646,
        capacite:4,
        tarif:'',
        duree:'',
    },
    {
        nom:'Mongie Tourmalet',
        type:'Studio',
        loc:'La Mongie',
        station:'La Mongie',
        ui:'OSMB-109624-1',
        pic:'mongie-tourmalet.jpg',
        lat:42.909463,
        lng:0.167796,
        capacite:4,
        tarif:'195',
        duree:'semaine',
    },
    {
        nom:'Mongie Tourmalet',
        type:'Studio',
        loc:'La Mongie',
        station:'La Mongie',
        ui:'OSMB-109624-2',
        pic:'mongie-tourmalet2.jpg',
        lat:42.909463,
        lng:0.167796,
        capacite:4,
        tarif:'220',
        duree:'semaine',
    },
    {
        nom:'Appartement 36m² - Parking - Cheminée',
        type:'Appartement',
        loc:'Cauterets',
        station:'Cauterets',
        ui:'OSMB-69994-1',
        pic:'appartement-36m2.jpg',
        lat:42.885360,
        lng:-0.111724,
        capacite:6,
        tarif:'350',
        duree:'semaine',
    },
    {
        nom:'Myrtilles 2',
        type:'Appartement',
        loc:'Piau Engaly',
        station:'Piau Engaly',
        ui:'OSMB-109515-1',
        pic:'myrtilles2.jpg',
        lat:42.783604,
        lng:0.158957,
        capacite:5,
        tarif:'150',
        duree:'semaine',
    },
    {
        nom:'T4 Lumineux 3 Chambres - 2 SDB - Plein centre et vue montage',
        type:'Appartement',
        loc:'Cauterets',
        station:'Cauterets',
        ui:'OSMB-73458-1',
        pic:'appartement-t4.jpg',
        lat:42.889714,
        lng:-0.116591,
        capacite:6,
        tarif:'495',
        duree:'semaine',
    },
    {
        nom:'Les Arroques, Villa La Cordée - Wifi et Parking',
        type:'Appartement',
        loc:'Cauterets',
        station:'Cauterets',
        ui:'OSMB-35729-4',
        pic:'les-arroques.jpg',
        lat:42.891247,
        lng:-0.110866,
        capacite:7,
        tarif:'485€',
        duree:'semaine',
    },
    {
        nom:'Le Mayouret, Villa La Cordée - Wifi et Parking',
        type:'Appartement',
        loc:'Cauterets',
        station:'Cauterets',
        ui:'OSMB-35729-1',
        pic:'le-mayouret.jpg',
        lat:42.891247,
        lng:-0.110866,
        capacite:6,
        tarif:'485',
        duree:'semaine',
    },
    {
        nom:'Altitude 1800',
        type:'Appartement',
        loc:'La Mongie',
        station:'La Mongie',
        ui:'OSMB-52041-1',
        pic:'altitude-1800.jpg',
        lat:42.910656,
        lng:0.173925,
        capacite:6,
        tarif:'200',
        duree:'semaine',
    },
    {
        nom:'Val Soleil',
        type:'Studio',
        loc:'Gourette',
        station:'Gourette',
        ui:'OSMB-109951-1',
        pic:'val-soleil.jpg',
        lat:42.959538,
        lng:-0.330323,
        capacite:4,
        tarif:'110',
        duree:'2 nuits',
    },
    {
        nom:'Les Oursons II',
        type:'Studio',
        loc:'lpsm',
        station:'lpsm',
        ui:'OSMB-43605-1',
        pic:'lesoursons2.jpg',
        lat:42.978179,
        lng:-0.746642,
        capacite:4,
        tarif:'170',
        duree:'semaine',
    },
    {
        nom:'Mongie Tourmalet',
        type:'Studio',
        loc:'La Mongie',
        station:'La Mongie',
        ui:'OSMB-109492-1',
        pic:'mongie-tourmalet3.jpg',
        lat:42.909433,
        lng:0.167747,
        capacite:5,
        tarif:'240',
        duree:'semaine',
    },
    {
        nom:'Appartement 34m²',
        type:'Appartement',
        loc:'Cauterets',
        station:'Cauterets',
        ui:'OSMB-92781-1',
        pic:'appartement34m2.jpg',
        lat:42.896347,
        lng:-0.115282,
        capacite:5,
        tarif:'300',
        duree:'semaine',
    },
    {
        nom:'Studio Centre Ville avec parking, ascenseur et wifi',
        type:'Studio',
        loc:'Cauterets',
        station:'Cauterets',
        ui:'OSMB-100554-1',
        pic:'studio-centreville.jpg',
        lat:42.890008,
        lng:-0.113860,
        capacite:4,
        tarif:'250',
        duree:'semaine',
    },
    {
        nom:'Myrtilles III',
        type:'Studio',
        loc:'Piau Engaly',
        station:'Piau Engaly',
        ui:'OSMB-64457-1',
        pic:'myrtilles3.jpg',
        lat:42.783604,
        lng:0.158957,
        capacite:4,
        tarif:'',
        duree:'',
    },
    {
        nom:'Valnéa',
        type:'Appartement',
        loc:'Peyragudes',
        station:'Peyragudes',
        ui:'OSMB-69002-1',
        pic:'valnea.jpg',
        lat:42.790074,
        lng:0.445631,
        capacite:6,
        tarif:'400',
        duree:'semaine',
    },
    {
        nom:'Appartement neuf tout confort à 5min du centre ville',
        type:'Appartement',
        loc:'Cauterets',
        station:'Cauterets',
        ui:'OSMB-66083-1',
        pic:'appartement-confort.jpg',
        lat:42.885916,
        lng:-0.112204,
        capacite:6,
        tarif:'550',
        duree:'semaine'
    },
    {
        nom:'APPARTEMENT CENTRE VILLE REFAIT À NEUF ',
        type:'Appartement',
        loc:'Cauterets',
        station:'Cauterets',
        ui:'OSMB-72743-1',
        pic:'appartement_centreville.jpg',
        lat:42.887092,
        lng:-0.113118,
        capacite:4,
        tarif:'300',
        duree:'semaine',
    },









    


];